apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler #Horizontal Pod Autoscaler automatically adjusts the number of replicas (pods) in a deployment based on CPU utilization.
metadata:
  name: myapp-hpa
  namespace: myapp-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
#If the average CPU utilization exceeds 50%, the HPA will scale up (add more pods), and if it goes below 50%, it will scale down