# This is a basic workflow to help you get started with Actions

name: CICD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Log in to Azure
      uses: azure/login@v1.4.7
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build & Push Docker Image
      run: |
        docker build -t testacr.azurecr.io/myapp:latest .
        docker login testacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push testacr.azurecr.io/myapp:latest

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group rg --name platformengtestresourcegroup
        kubectl apply -f k8s/
